#on: [push, pull_request]
#on: [pull_request]
# Trigger the workflow on push to master (ignoring .md only changes)
# Trigger the workflow on any pull_request (ignoring .md only changes)
# Enable manual triggering (important for contributors to enable a check on their fork)
# If a build is running in the current branch, and the branch is updated, we cancel the previous build and start
# a new one with the updated changes.
# Run checkstyle validations for pipeline
# ./run_core_generators.sh automatically runs ./mvnw spotless:apply

name: Modified Check codegen and formatting
jobs:
  checkstyle_check:
    name: checkstyle_check
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-checkstyle_check.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/javaparser/javaparser', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Checkout latest code
      uses: actions/checkout@v4.2.0
      with:
        fetch-depth: '0'
    - run: touch optcd-3.txt
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: zulu
    - run: touch optcd-4.txt
    - name: Validate Project Checkstyle
      run: ./mvnw -B checkstyle:check
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-checkstyle_check
        path: /home/runner/inotifywait-log-checkstyle_check.csv
  spotless_check:
    name: spotless_check
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-spotless_check.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/javaparser/javaparser', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Checkout latest code
      uses: actions/checkout@v4.2.0
      with:
        fetch-depth: '0'
    - run: touch optcd-3.txt
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: zulu
    - run: touch optcd-4.txt
    - name: Generate code and format
      run: |-
        ./run_core_metamodel_generator.sh
        # ./run_core_generators.sh automatically runs ./mvnw spotless:apply
        ./run_core_generators.sh
        git diff --exit-code
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-spotless_check
        path: /home/runner/inotifywait-log-spotless_check.csv
'on':
- push
- workflow_dispatch
